// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuditFields struct {
	CreatedAt int     `json:"createdAt"`
	CreatedBy string  `json:"createdBy"`
	UpdatedAt *int    `json:"updatedAt"`
	UpdatedBy *string `json:"updatedBy"`
}

type ChangePasswordRequest struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type CommonErrorResponse struct {
	Field   *string `json:"field"`
	Message *string `json:"message"`
}

type CommonPostResponse struct {
	Errors []*Error     `json:"errors"`
	Post   *PartialPost `json:"post"`
}

type CommonPostsResponse struct {
	Errors []*Error       `json:"errors"`
	Posts  []*PartialPost `json:"posts"`
}

type CommonSourceResponse struct {
	Errors  []*Error       `json:"errors"`
	Sources *PartialSource `json:"sources"`
}

type CommonSourcesResponse struct {
	Errors  []*Error         `json:"errors"`
	Sources []*PartialSource `json:"sources"`
}

type CommonUserResponse struct {
	Errors []*Error     `json:"errors"`
	User   *PartialUser `json:"user"`
}

type CommonUsersResponse struct {
	Errors []*Error       `json:"errors"`
	User   []*PartialUser `json:"user"`
}

type CreatePostRequest struct {
	Title   string `json:"title"`
	Comment string `json:"comment"`
	URL     string `json:"url"`
}

type DeletePostRequest struct {
	PostID string `json:"postID"`
}

type Error struct {
	Field   *string `json:"field"`
	Message *string `json:"message"`
}

type FollowRequest struct {
	FollowedID string `json:"followedID"`
}

type FullPost struct {
	Post     *PartialPost `json:"post"`
	LinkID   string       `json:"linkID"`
	SourceID string       `json:"sourceID"`
}

type FullUser struct {
	User    *PartialUser `json:"user"`
	Details *UserDetails `json:"details"`
}

type LoginUserRequest struct {
	UsernameOrEmail string `json:"usernameOrEmail"`
	Password        string `json:"password"`
}

type PartialPost struct {
	ID      string `json:"id"`
	UserID  string `json:"userID"`
	LinkURL string `json:"linkURL"`
	Comment string `json:"comment"`
}

type PartialSource struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Organization string `json:"organization"`
}

type PartialUser struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

type PostsRequest struct {
	UserID string `json:"userID"`
}

type RegisterUserRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdatePostRequest struct {
	Title   string `json:"title"`
	Comment string `json:"comment"`
	URL     string `json:"url"`
}

type UserDetails struct {
	DisplayName *string `json:"displayName"`
	Description *string `json:"description"`
}
